- tuj/java/tStandardizePhoneNumber_Feature6067/process/tStandardizePhoneNumber_Feature6067_0.1.item
- tuj/java/tStandardizePhoneNumber_Feature6067/process/tStandardizePhoneNumber_Feature6067_0.1.properties
- tuj/java/tStandardizePhoneNumber_Feature6067/ref.csv
- tuj/java/tStandardizePhoneNumber_Feature6067/talend.project
Because of new jar has been added.
> bug fixed TDQ-10782 modify the Result of the TUJ.

- tuj/java/tDuplicateRow_TDQ8433/process/tujs/tDuplicateRow_TDQ8433_0.1.item
- tuj/java/tDuplicateRow_TDQ8433/process/tujs/tDuplicateRow_TDQ8433_0.1.properties
- tuj/java/tQASAddressRow_TDQ8847/process/tujs/tQASAddressRow_TDQ8847_0.1.item
- tuj/java/tQASAddressRow_TDQ8847/process/tujs/tQASAddressRow_TDQ8847_0.1.properties
- tuj/java/tReservoirSampling_TDQ8766/process/tujs/tReservoirSampling_TDQ8766_0.1.item
- tuj/java/tReservoirSampling_TDQ8766/process/tujs/tReservoirSampling_TDQ8766_0.1.properties
- tuj/java/tReservoirSampling_TDQ8766/talend.project
> bug fixed TDQ-10841

- tuj/java/tMDMBulkLoad_novalid_genid/process/TUJ/tMDMBulkLoad_novalid_genid_0.1.item
- tuj/java/tMDMInput_conditions/MDMEEPRODUCTDEMO/process/TUJ/tMDMInput_conditions_0.1.item
- tuj/java/tMDMInput_paging/TESTS/process/TUJ/tMDMInput_paging_0.1.item
- tuj/java/tMDMOutput_collections/MDMEEPRODUCTDEMO/process/TUJ/tMDMOutput_collections_0.1.item
- Use password from context instead of a static value
> TMDM-8946 Fix existing mdm tujs tMDMInput_conditions, tMDMInput_paging, tMDMOutput_collections, tMDMBulkLoad_novalid_genid.

- tuj/java/BugTDI31380_tDB2Output_Parallel/process/BugTDI31380_tDB2Output_Parallel_0.1.item
- tuj/java/feature4166_tConvertType_autocast_7/process/feature4166_tConvertType_autocast_7_0.1.item
- tuj/java/feature4166_tConvertType_man_2/process/feature4166_tConvertType_man_2_0.1.item
- tuj/java/tFileExist_NotExist/process/components/tFileExist/tFileExist_NotExist_0.1.item
https://jira.talendforge.org/browse/TDI-37957
> TDI-37957:Some TUJ generate code failed

- tuj/java/TDI35262_tOracleBulk_Password_Append/LOCAL_PROJECT/process/TDI35262_tOracleBulk_Password_Append_0.1.item
https://jira.talendforge.org/browse/TDI-39135
> fix(TDI-39135):Change TUJ variable name in tJava

- tuj/java/BugTDI29033_tMSSqlOutput_Delete_SupportNull/process/BugTDI29033_tMSSqlOutput_Delete_SupportNull_0.1.item
- tuj/java/BugTDI29033_tMSSqlOutput_MidDyn_Delete_SupportNull/process/BugTDI29033_tMSSqlOutput_MidDyn_Delete_SupportNull_0.1.item
- tuj/java/BugTDI29033_tMSSqlOutput_Update_SupportNull/process/BugTDI29033_tMSSqlOutput_Update_SupportNull_0.1.item
https://jira.talendforge.org/browse/TDI-39016
> fix(TDI-39016):amend some tmssql tujs

- tuj/java/tMultiPatternCheck_10269_tuj/process/tujs/tMultiPatternCheck_10269_tuj_0.1.item
- tuj/java/tMultiPatternCheck_10269_tuj/process/tujs/tMultiPatternCheck_10269_tuj_0.1.properties
- tuj/java/tMultiPatternCheck_10269_tuj/talend.project
upgrate tMultiPatternCheck_10269_tuj to new version
> bug fixed TDQ-14441 upgrate tMultiPatternCheck_10269_tuj to new version

- tuj/java/TDI38068_tSnowflake_Dyna_delete/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_delete_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_insert_1_Full/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_insert_1_Full_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_insert_2_Head/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_insert_2_Head_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_insert_3_Middle/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_insert_3_Middle_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_insert_4_Tail/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_insert_4_Tail_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_update_1_Full/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_update_1_Full_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_update_2_Head/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_update_2_Head_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_update_3_Middle/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_update_3_Middle_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_update_4_Tail/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_update_4_Tail_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_upsert_1_Full/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_upsert_1_Full_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_upsert_2_Head/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_upsert_2_Head_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_upsert_3_Middle/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_upsert_3_Middle_0.1.item
- tuj/java/TDI38068_tSnowflake_Dyna_upsert_4_Tail/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Dyna_upsert_4_Tail_0.1.item
- tuj/java/TDI38068_tSnowflake_NB_LINE/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_NB_LINE_0.1.item
- tuj/java/TDI38068_tSnowflake_Reject_line/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Reject_line_0.1.item
- tuj/java/TDI38068_tSnowflake_Role/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Role_0.1.item
- tuj/java/TDI38068_tSnowflake_Special_data_mapping/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Special_data_mapping_0.1.item
- tuj/java/TDI38068_tSnowflake_Tracing/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_Tracing_0.1.item
- tuj/java/TDI38068_tSnowflake_column_order/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_column_order_0.1.item
- tuj/java/TDI38068_tSnowflake_delete/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_delete_0.1.item
- tuj/java/TDI38068_tSnowflake_insert/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_insert_0.1.item
- tuj/java/TDI38068_tSnowflake_update/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_update_0.1.item
- tuj/java/TDI38068_tSnowflake_upsert/LOCAL_PROJECT/process/TDI38068_SnowFlake_auto/TDI38068_tSnowflake_upsert_0.1.item
- tuj/java/TDI38133_tSnowflake_date_time_conversion/LOCAL_PROJECT/process/TDI38133_tSnowflake_date_time_conversion_0.1.item
- tuj/java/TDI38141_tSnowflake_Time_field/LOCAL_PROJECT/process/TDI38141_tSnowflake_Time_field_0.1.item
- tuj/java/TDI38145_tSnowflake_date_format/LOCAL_PROJECT/process/TDI38145_tSnowflake_date_format_0.1.item
- tuj/java/TDI38186_tSnowflakeconnection/LOCAL_PROJECT/process/TDI38186_tSnowflakeconnection_0.1.item
- tuj/java/TDI38200_tSnowflakeInput_Null_cause_NPE/LOCAL_PROJECT/process/TDI38200_tSnowflakeInput_Null_cause_NPE_0.1.item
Changed snowflake driver version to newest one 3.3.2
> fix(TDI-39750): fix tujs on maintenance/6.4 related to snowflake

- tuj/java/Databases/PostgreSQL/BugTDI32594_tELTPostgresqlOutput_ColFunc/process/BugTDI32594_tELTPostgresqlOutput_ColFunc_0.1.item
For https://jira.talendforge.org/browse/TDI-39833
Fix tuj BugTDI32594_tELTPostgresqlOutput_ColFunc which was broken by last modification.
> fix(TDI-39833):tuj BugTDI32594_tELTPostgresqlOutput_ColFunc failed.

- tuj/java/Databases/JDBC/TDI39519_tJDBCSCDELT_Snow_DataType/LOCAL_PROJECT/process/TDI39519_tJDBCSCDELT_Snow_DataType_0.1.item
- tuj/java/Databases/JDBC/TDI39519_tJDBCSCDELT_Snow_TableAction_1/LOCAL_PROJECT/process/TDI39519_tJDBCSCDELT_Snow_TableAction_1_0.1.item
- tuj/java/Databases/JDBC/TDI39519_tJDBCSCDELT_Snow_TableAction_2/LOCAL_PROJECT/process/TDI39519_tJDBCSCDELT_Snow_TableAction_2_0.1.item
- tuj/java/Databases/JDBC/TDI39519_tJDBCSCDELT_Snow_sequence/LOCAL_PROJECT/process/TDI39519_tJDBCSCDELT_Snow_sequence_0.1.item
- tuj/java/Databases/JDBC/TDI39519_tJDBCSCDELT_Snow_sequence2/LOCAL_PROJECT/process/TDI39519_tJDBCSCDELT_Snow_sequence2_0.1.item
Upgrading Snowflake driver version from 3.3.2 to newest 3.5.3
Related Jira - https://jira.talendforge.org/browse/TDI-40475
> fix(TDI-40475): upgrade snowflake driver to 3.5.3 in tuj

- tuj/java/Misc/DeactivatedComponent/process/demo/DeactivatedComponent_0.1.item
https://jira.talendforge.org/browse/TTP-65
Fix resource location
> fix(TTP-65) : fix resource location

- tuj/java/Databases/Oracle/feature4015_oracle_insert/process/feature/feature4015_oracle_insert_0.1.item
- tuj/java/Databases/Oracle/feature4015_oracle_insertorupdate/process/feature/feature4015_oracle_insertorupdate_0.1.item
- tuj/java/Databases/Oracle/feature4015_oracle_update/process/feature/feature4015_oracle_update_0.1.item
- tuj/java/Databases/Oracle/feature4015_oracle_updateorinsert/process/feature/feature4015_oracle_updateorinsert_0.1.item
https://jira.talendforge.org/browse/TDI-41157
> fix(TDI-41157): modify oracle tuj

- tuj/java/DataQuality/tJapaneseTransliterate_TDQ15286/process/tujs/tJapaneseTransliterate_TDQ15286_0.1.item
- tuj/java/DataQuality/tJapaneseTransliterate_TDQ15286/process/tujs/tJapaneseTransliterate_TDQ15286_0.1.properties
> chore(TDQ-16195): revert the changes for TDQ-15960 & TDQ-15774, fix version 7.2 only

- tuj/java/DataQuality/tJapaneseNumberNormalize_TDQ15413/process/tujs/tJapaneseNumberNormalize_TDQ15413_0.1.item
- tuj/java/DataQuality/tJapaneseNumberNormalize_TDQ15413/process/tujs/tJapaneseNumberNormalize_TDQ15413_0.1.properties
- tuj/java/DataQuality/tJapaneseNumberNormalize_TDQ15413/talend.project
> TDQ-16518 update the TUJ tJapaneseNumberNormalize_TDQ15413 to adapt for

- templates/README.md
Need more explanation about TALEND_PARTIAL_GIT_BRANCH
> More explanation about TALEND_PARTIAL_GIT_BRANCH

- tuj/java/DataQuality/tMatchGroup_TDQ10958_withBlock_disk_Block_value_is_null/process/tMatchGroup/tMatchGroup_TDQ10958_withBlock_disk_Block_value_is_null_0.1.item
- tuj/java/DataQuality/tMatchGroup_TDQ10958_withBlock_disk_Block_value_is_null/process/tMatchGroup/tMatchGroup_TDQ10958_withBlock_disk_Block_value_is_null_0.1.properties
- tuj/java/DataQuality/tMatchGroup_TDQ10958_withBlock_disk_Block_value_is_null/talend.project
- tuj/java/DataQuality/tMatchGroup_TDQ10958_withBlock_disk_Block_value_is_null/unique_rows_ref.csv
> chor(TDQ-10958 TDQ-17170): add TUJ case for tmatchGroup component block+ Store on disk + block column take null value

- tuj/java/DataQuality/tMatchGroup_TDQ11933_uncheck_sort_by_gid_index_mode/process/tMatchGroup/tMatchGroup_TDQ11933_uncheck_sort_by_gid_index_mode_0.1.item
- tuj/java/DataQuality/tMatchGroup_TDQ11933_uncheck_sort_by_gid_uuid_mode/process/tMatchGroup/tMatchGroup_TDQ11933_uncheck_sort_by_gid_uuid_mode_0.1.item
> chor(TDQ-11933): Modify TUJ case to setting correctly path of reference file

- tuj/java/DataQuality/tPatternMasking_TDQ17177_support_raw_output_flow/checkAllMain_ref.csv
- tuj/java/DataQuality/tPatternMasking_TDQ17177_support_raw_output_flow/checkAllRaw_ref.csv
- tuj/java/DataQuality/tPatternMasking_TDQ17177_support_raw_output_flow/noOriginalMainRaw_ref.csv
- tuj/java/DataQuality/tPatternMasking_TDQ17177_support_raw_output_flow/noOriginalMain_ref.csv
- tuj/java/DataQuality/tPatternMasking_TDQ17177_support_raw_output_flow/noOriginalNoRawFlowMain_ref.csv
- tuj/java/DataQuality/tPatternMasking_TDQ17177_support_raw_output_flow/noThingChoosMain_ref.csv
- tuj/java/DataQuality/tPatternMasking_TDQ17177_support_raw_output_flow/process/tPatternMasking/tPatternMasking_TDQ17177_support_raw_output_flow_0.1.item
- tuj/java/DataQuality/tPatternMasking_TDQ17177_support_raw_output_flow/process/tPatternMasking/tPatternMasking_TDQ17177_support_raw_output_flow_0.1.properties
- tuj/java/DataQuality/tPatternMasking_TDQ17177_support_raw_output_flow/talend.project
> feat(TDQ-17177): Retrieve records "rejected" by the tPatternMasking component only on DI job added TUJ

- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCard/maskcard_AES_ref.csv
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCard/maskcard_SHA_2_ref.csv
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCard/maskcard_basic_ref.csv
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCard/process/tDataMasking_TDQ17148_MaskCreditCard_0.1.item
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCard/process/tDataMasking_TDQ17148_MaskCreditCard_0.1.properties
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCard/talend.project
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCardKeepBank/maskcardKeepBank_AES_ref.csv
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCardKeepBank/maskcardKeepBank_SHA_2_ref.csv
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCardKeepBank/maskcardKeepBank_basic_ref.csv
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCardKeepBank/process/tDataMasking_TDQ17148_MaskCreditCardKeepBank_0.1.item
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCardKeepBank/process/tDataMasking_TDQ17148_MaskCreditCardKeepBank_0.1.properties
- tuj/java/DataQuality/tDataMasking_TDQ17148_MaskCreditCardKeepBank/talend.project
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCard/Unmaskcard_AES_ref.csv
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCard/Unmaskcard_SHA_2_ref.csv
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCard/process/tDataUnmasking_TDQ17148_MaskCreditCard_0.1.item
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCard/process/tDataUnmasking_TDQ17148_MaskCreditCard_0.1.properties
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCard/talend.project
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCardKeepBank/UnmaskcardKeepBank_AES_ref.csv
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCardKeepBank/UnmaskcardKeepBank_SHA_2_ref.csv
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCardKeepBank/process/tDataUnmasking_TDQ17148_MaskCreditCardKeepBank_0.1.item
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCardKeepBank/process/tDataUnmasking_TDQ17148_MaskCreditCardKeepBank_0.1.properties
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCardKeepBank/talend.project
> feat(TDQ-17148 TDQ-17406): create TUJ for Support FPE for credit card function in tData(Un)Masking on DI job

- templates/README.md
Update of Colibri Address which was leading to an obsolete page.
> Update of Colibri Address

- tuj/java/Databases/Neo4j/TDI39293_tNeo4jRow_tNeo4jInput_NBLine/process/Neo4j/TDI39293_tNeo4jRow_tNeo4jInput_NBLine_0.1.item
- tuj/java/Databases/Neo4j/TDI39293_tNeo4jRow_tNeo4jInput_Remote/process/Neo4j/TDI39293_tNeo4jRow_tNeo4jInput_Remote_0.1.item
- tuj/java/Databases/Neo4j/TDI39725_tNeo4jInput_ReadMultipleNodes/process/Neo4j/TDI39725_tNeo4jInput_ReadMultipleNodes_0.1.item
https://jira.talendforge.org/browse/TDI-43163
> fix(TDI-43163):change path contexts neo4j

- tuj/java/Databases/Neo4j/TDI39293_tNeo4jRow_tNeo4jInput_NBLine/process/Neo4j/TDI39293_tNeo4jRow_tNeo4jInput_NBLine_0.1.item
https://jira.talendforge.org/browse/TDI-43163
> fix(TDI-39293):add tag

- tuj/java/Databases/MySQL/bug12783_tMysqlOutput_ContVar/process/blazer/database/Mysql/bug12783_tMysqlOutput_ContVar_0.1.item
- tuj/java/Databases/MySQL/feature9821_tMysqlOutput_InsertIgnore/process/blazer/database/Mysql/feature9821_tMysqlOutput_InsertIgnore_0.1.item
TDI-43510 Change two mysql tuj to adapt remove mysql4
> TDI-43510 Change two mysql tuj to adapt remove mysql4

- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCardKeepBank/UnmaskcardKeepBank_AES_ref.csv
- tuj/java/DataQuality/tDataUnmasking_TDQ17148_MaskCreditCardKeepBank/UnmaskcardKeepBank_SHA_2_ref.csv
cause by commit:https://github.com/Talend/data-quality-ee/commit/ce3ac5d1c9b6e4ec157b066e8383acad7312368a
> fix(TDQ-18882): update result to remove some invalid format.

- tuj/java/TalendMDM/tMDMViewSearch_CustomFilter/ActiveFalse_reference.csv
- tuj/java/TalendMDM/tMDMViewSearch_MultipleOperations/ViewSearchMultipleOperations_results_11_reference.csv
- tuj/java/TalendMDM/tMDMViewSearch_MultipleOperations/ViewSearchMultipleOperations_results_all_reference.csv
https://jira.talendforge.org/browse/TMDM-14929
> TMDM-14929 [QA][TUJ] tMDMViewSearch_MultipleOperations and tMDMViewSearch_CustomFilter assert failed

- tuj/java/CustomCode/tJava_with_import_feature2812/process/Processing/tJava/tJava_with_import_feature2812_0.1.item
> TDI-45332_updatejar

- tuj/java/DataQuality/tMatchGroup_VSR_ContextTabConfidence/.settings/migration_task.index
- tuj/java/DataQuality/tMatchGroup_VSR_ContextTabConfidence/.settings/project.settings
- tuj/java/DataQuality/tMatchGroup_VSR_ContextTabConfidence/.settings/relationship.index
- tuj/java/DataQuality/tMatchGroup_VSR_ContextTabConfidence/process/tMatchGroup_VSR_ContextTabConfidence_0.1.properties
- tuj/java/DataQuality/tMatchGroup_VSR_ContextTabConfidence/process/tMatchGroup_VSR_ContextTabConfidence_sub_0.1.properties
- tuj/java/DataQuality/tMatchGroup_swoosh_ContextTab_Confidence/.settings/migration_task.index
- tuj/java/DataQuality/tMatchGroup_swoosh_ContextTab_Confidence/.settings/project.settings
- tuj/java/DataQuality/tMatchGroup_swoosh_ContextTab_Confidence/.settings/relationship.index
- tuj/java/DataQuality/tMatchGroup_swoosh_ContextTab_Confidence/process/tMatchGroup_swoosh_ContextTab_Confidence_0.1.properties
- tuj/java/DataQuality/tMatchGroup_swoosh_ContextTab_Confidence/process/tMatchGroup_swoosh_ContextTab_Confidence_sub_0.1.item
- tuj/java/DataQuality/tMatchGroup_swoosh_ContextTab_Confidence/process/tMatchGroup_swoosh_ContextTab_Confidence_sub_0.1.properties
fix the failed tuj, help to review it.
> fix(TDQ-18848):resolved the failed TUJ

- .idea/workspace.xml
Hello,
There is a TUJ:
tuj\java\NetsuiteV2019\TDI45879_tNetsuiteV2019Input_nb_line_not_getnull_norecord_73
Oleksandra
> TDI45879_tNetsuiteV2019Input_nb_line_not_getnull_norecord

- tuj/java/DataQuality/tdqReportRun_TDQ19434_file_connection_first_job/process/tdqReportRun_TDQ19434_file_connection_first_job_0.1.item
- tuj/java/DataQuality/tdqReportRun_TDQ19434_file_connection_first_job/process/tdqReportRun_TDQ19434_file_connection_first_job_0.1.properties
- tuj/java/DataQuality/tdqReportRun_TDQ19434_file_connection_first_job/ref/TDQ_Data_Profiling/Analyses/col2_0.1.ana
- tuj/java/DataQuality/tdqReportRun_TDQ19434_file_connection_first_job/ref/TDQ_Data_Profiling/Analyses/col2_0.1.properties
- tuj/java/DataQuality/tdqReportRun_TDQ19434_file_connection_first_job/ref/TDQ_Data_Profiling/report/col2_0.1.properties
- tuj/java/DataQuality/tdqReportRun_TDQ19434_file_connection_first_job/ref/TDQ_Data_Profiling/report/col2_0.1.rep
- tuj/java/DataQuality/tdqReportRun_TDQ19434_file_connection_first_job/ref/metadata/fileDelimited/file1_0.1.item
- tuj/java/DataQuality/tdqReportRun_TDQ19434_file_connection_first_job/ref/metadata/fileDelimited/file1_0.1.properties
- tuj/java/DataQuality/tdqReportRun_TDQ19434_file_connection_first_job/talend.project
> chor(TDQ-19434): create first tdqReportRun component TUJ case(file
